### PR TITLE
Add optical flow sampling code/doc and example

### PR DESCRIPTION
**Pull request by infinity1096**

### CODE REVIEW

**Comment by yoraish** [comment]
Hello hello!
@Amigoshan, I added you as admin to this repo. Happy to help further if needed, also :-).

**Comment by Nik-V9** [comment]
@infinity1096 Some of the images linked in the examples.rst file are missing in the commit.

**Comment by Nik-V9** [comment]
@infinity1096 Yuchen, let's update the pull request to remove the hardcoded 0.5 fix. Ideally, you only need to change the intrinsics (K) matrix once to ensure correct projection everywhere.

Once, that is done, I can do to a code review and help merge this pull request. Thanks!

**Review by Amigoshan — APPROVED** [review]

**Comment by Nik-V9** [comment]
@Amigoshan This branch was not ready for merge 😅 @infinity1096 needed to update the code to fix the harcoding.

**Pull request merged**
